### ISSUE TITLE
Quotation Mark Transformation enhancement

### ISSUE THREAD

**Issue by AMD921** [mzn928/Aegisub_Persian-Toolkit#1]
>Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,‫"الف ب پ ت ث."

Paknevised: 

>Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,‫ «الف ب پ ت ث.»

Issue:
>Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,‫"الف
Dialogue: 0,0:00:05.00,0:00:07.00,Default,,0,0,0,,ب
Dialogue: 0,0:00:07.00,0:00:09.00,Default,,0,0,0,,پ
Dialogue: 0,0:00:09.00,0:00:11.00,Default,,0,0,0,,ت
Dialogue: 0,0:00:11.00,0:00:13.00,Default,,0,0,0,,‫ث."

Paknevis isn't functional in this case.

**Comment by mzn928** [comment]
this is not the intended use case for this function
